# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "back/package-lock.json"
    
    - name: Install dependencies
      working-directory: back
      run: npm ci

    - name: Lint
      working-directory: back
      run: npm run lint 
      continue-on-error: true

    - name: Type check
      working-directory: back
      run: npx tsc --noEmit
      continue-on-error: true

    - name: Generate routes
      working-directory: back
      run: npm run generate

    - name: Build
      working-directory: back
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./back
        push: true
        tags: |
          zolasriben/backend:${{ github.sha }}
          zolasriben/backend:latest
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.description=Backend API for ${{ github.repository }}
