# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "back/package-lock.json"
    
    - name: Install dependencies
      working-directory: back
      run: npm ci

    - name: Lint
      working-directory: back
      run: npm run lint 
      continue-on-error: true

    - name: Type check
      working-directory: back
      run: npx tsc --noEmit

    - name: Generate routes
      working-directory: back
      run: npm run generate

    - name: Build
      working-directory: back
      run: npm run build

    - name: Build Docker image
      working-directory: back
      run: docker build -t backend:${{ github.sha }} .
